[package]
name = "mserver"
version = "0.1.0"
edition = "2021"

[dependencies]
markdown = "0.3"
directories = "4.0.1"
toml = "0.5.8"
serde = { version = "1.0.132", features = ["derive"] }
daemonize = "0.4.1"